# Setup
title: Abdul Aziz
url: https://azizali.me
baseurl: ""
paginate: 5
permalink: pretty

include: ["_pages"]

# About/contact
author:
  name: Abdul Aziz
  url: https://github.com/dotaziz
  email: azizalialhassan@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #
